language: c
compiler:
  - clang
  - gcc-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - cmake
      - cmake-data
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./myfind
  - gcov CMakeFiles/myfind.dir/main.c.o
before_install:
  - pip install --user codecov
after_success:
  - codecov
