language: c
compiler:
  - gcc
  - clang
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./myfind
  - if [ "$CC" == "gcc" ]; then gcov-5 CMakeFiles/*/*.o; fi
after_success:
  - if [ "$CC" == "gcc" ]; then bash <(curl -s https://codecov.io/bash); fi

