language: c
compiler:
  - gcc-5
  - clang-3.7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # gcc
      - llvm-toolchain-precise-3.7 # llvm
      - george-edison55-precise-backports # cmake
    packages:
      - gcc-5
      - clang-3.7
      - cmake
      - cmake-data
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./myfind
  - gcov-5 */*/*.o # CMakeFiles/myfind.dir/*.o
after_success:
  - bash <(curl -s https://codecov.io/bash)
