env:
  global:
   - secure: "RzQk/MPhK2G2kA7FwnnvNsno+wpfbrtTp4aLhzCuCSVfoix4DAhMdnbcp1RDKtpj+9YZXrm3urjaf349Zq5KBop666eAgq0fId0sxmIczNebhE32VHa6CvSur55Sro1ycbeUM8y1fof1OpzZ3tlQR9BW1pxAsZiMH/D1SM/L7mMcJIH++5MP2hntAE8RzD6UXv1Ww8uc3JUQJK00KffrpZjvSDR+7qnwjl2Tz4cclBZZIhg9s9tgcSBRCh52B+g24AM2oZNkFEjQMHh0HJ6eeZ25TrEL5RuzF8jR49ZQh8rnOfPxdA27S4XFiICRfXkDHYQCNDxIYZtMJmk8P6164I85p7eIbdU8CzJeSO+BeVQeKfuJU9hDHdGCBz9ufuzw3IMM9i03uN0YUiCjcv6tYJVqewMuEX8WAayiwAGHw8/vuhnVl1jlHWqOEFBz411FjeyNUrpecHUakMTVA1rzp/6YLNsaFR45LtyKLS8OX2R04bMNyZUBxUrIqAySYW3t2CvU3TTVtV2GfGJZIoS/w9EYVVlPOFxpaB3CARbtEk8/qNqpbegordy1aB7Hkh0F4L+P2iDJJ/sO2A8bYo5nmKq4W6AxKUYbhW00GeOnrpQe75ymy1UPuKueZzzT2YHXhPc7jifqwo1Q3gGzrkIOIGorW+4tAqQgpVxmKRdA1G4="
language: c
compiler:
  - gcc
addons:
  coverity_scan:
    project:
      name: "amq/myfind"
      description: "Learning C: a GNU find clone"
    notification_email: "amq@users.noreply.github.com"
    build_command_prepend: "mkdir -p build; cd build; cmake .."
    build_command: "cmake --build ."
    branch_pattern: coverity_scan
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make