language: c
compiler:
  - gcc-5
  - clang-3.7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # gcc
      - llvm-toolchain-precise-3.7 # cmake
      - george-edison55-precise-backports # cmake
    packages:
      - gcc-5
      - clang-3.7
      - cmake
      - cmake-data
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./myfind
  - if [ "$CC" == "gcc-5" ]; then gcov-5 CMakeFiles/*/*.o; fi
after_success:
  - if [ "$CC" == "gcc-5" ]; then bash <(curl -s https://codecov.io/bash); fi
env:
  global:
    secure: aJXNu83iW6b/xRMpZtHvtBrvO70i6m8ElMDiM663Bu8F/hj300OMtupmLy0c+/N5/W1D0ltGxcMiHizB3oXvqm6EgcOySuhgeS34Jfq+Wl5lL7iobnj0W1sua3YVSQGjz+61EZjlSYl6WDymBVHxAnVzJcGv+HPWiClXH2WUKEwexDMeFPavzNqdIzjutcUVBfIigP3CabLNYQ7rFtJDt7h66glrCgcYr4hhka7FYAnsY5CTV3FjL33NumVIgLKajrOh2xLXXURdKu6SBK2k535U5YUtVuPbhfJqMn/D0147RdH6L55owU4+cxlK42Xw1Qekbp0D8qnaeq3VxO/CDPIAP+M1zMJQ5+c4t97bzYkafp/IE7YaaQznlN3xA9vl1sGnOHVzYQACH/cIhhq5I8YfM41Xd1WX/1AMjiYepZM0iNEiEOu9RtEKoXSlCQ7hxlzmfcWHBWpgZbL8pDmFCAtdqdkj/Wq5QsRVwg8IXS7w6eybv7Vm+l7V5oK1xwxu6o+He0UjDogTF76fbRAZjv3nXhfIf790/gfgJNX7qPGAn/6ygAr5XGT8evyXY+owGHEIxFJRlahXsMv/EeBJtMdscuz19kCEtLbLLJIHlZKtqa1nurkAAYKlun6JyZHSDtba8VQ0Gxw98lun0wUy/38xa1SFynjoznWIi3UPRr4=
