language: c
compiler:
  - gcc-5
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - clang-3.7
      - cmake
      - cmake-data
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./myfind
  - gcov CMakeFiles/myfind.dir/main.c.o
after_success:
  - bash <(curl -s https://codecov.io/bash)